### ISSUE TITLE
function where 改成这样，可以实现$where['id']=['<',5];

### ISSUE THREAD

**Issue by pengxiaoyang123** [ninvfeng/mysql#2]
### public function where($where,$param=[]){
        if($param){
            $this->_param=array_merge($this->_param,$param);
        }
        if(is_array($where)){
            $res='';
            foreach($where as $k => $v){
                $column_key='';
                foreach (explode('.',$k) as $kk => $vv) {
                    $column_key.=' `'.$vv.'`.';
                    $column_plac='where_'.$vv;
                }
                if(is_array($v)){
                    $op = ' '.$v[0].' ';
                    $this->_param[$column_plac]=$v[1];
                }else{
                    $op = ' = ';
                    $this->_param[$column_plac]=$v;
                }
                $column_key=trim($column_key,'.');
                $res.=$column_key.$op.':'.$column_plac.' and';
            }
            $where=trim($res,'and');

        }
        $this->_where.=' '.$where.' and';

        return $this;
    }

**function where 改成这样，可以实现
$where['id']=['<',5];
$where['name']=['like','%wang%'];
db('user')->where($where)->select();
**

**Comment by ninvfeng** [comment]
已更新, 非常感谢
